name: daily

on:
  schedule:
  - cron: '* * * * *'
  push:
  - main


jobs:
  cron:
    runs-on: ubuntu-lastest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: CI
        run: |
          npm ci

      - name: Run Cron
        run: |
          npm run notification